const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const js = fs.readFileSync(path.join(root, "src", "idu-plus.js"), "utf8");
const css = fs.readFileSync(path.join(root, "src", "idu-plus.css"), "utf8");

assert(
  js.includes('const isForumPagePath = (pathname = window.location.pathname) =>') &&
    js.includes('/^\\/forums(?:\\/|$)/.test(pathname)') &&
    js.includes('/^\\/forum\\/(?:search|topics)(?:\\/|$)/.test(pathname)') &&
    !/Boolean\([\s\S]{0,100}\.forum-table/.test(js.slice(js.indexOf("const markPageType"), js.indexOf("const enhanceForumPages"))),
  "Only real forum routes should mark the whole page as a forum"
);

assert(
  /const isMessagesPagePath = [\s\S]*internal_messages/.test(js) &&
    /root\.classList\.toggle\("idu-messages-page", isMessagesPagePath\(\) \|\| Boolean\(messagesModule\)\)/.test(js) &&
    /form\.message_transport_search/.test(js),
  "Every internal-message folder should receive the messages page treatment"
);

for (const route of [
  "/internal_messages",
  "/internal_messages/drafts",
  "/internal_messages/sent",
  "/internal_messages/trash",
  "/internal_messages/new"
]) {
  assert(js.includes(`"${route}"`), `Message navigation should expose ${route}`);
}

assert(
  /className = "idu-page-tools idu-message-folders idu-generated"/.test(js) &&
    /aria-current", "page"/.test(js) &&
    /html\.idu-plus \.idu-page-tools/.test(css) &&
    /overflow-x: auto;/.test(css),
  "Message folders should use an accessible, narrow-screen-safe horizontal navigation"
);

assert(
  js.includes('{ href: "/forum/search", label: labels.search') &&
    /className = "idu-page-tools idu-forum-tools idu-generated"/.test(js),
  "Real forum pages should expose the built-in forum search"
);

assert(
  /forumLink\.setAttribute\("href", "\/forums"\)/.test(js) &&
    /forumLink\.removeAttribute\("onclick"\)/.test(js) &&
    /event\.stopImmediatePropagation\(\)/.test(js),
  "The topbar Forum action should navigate to /forums instead of reopening IDU's legacy popup"
);

assert(
  /accountActions\.insertBefore\(accountAction, logoutAction\)/.test(js),
  "The profile action should be placed immediately before logout in the topbar"
);

assert(
    /a\.fancybox\[href\^="#description_for_grade_"\]/.test(js) &&
    /aria-haspopup", "dialog"/.test(js) &&
    /clone\.querySelectorAll\("script, style"\)/.test(js) &&
    /const closeForm = document\.createElement\("form"\)/.test(js) &&
    /closeForm\.method = "dialog"/.test(js) &&
    /dialog\.append\(header, content\)/.test(js) &&
    /const closeGradeDetailsDialog = \(dialog\) => \{/.test(js) &&
    /closeButton\.closest\("dialog"\)/.test(js) &&
    /html\.idu-plus \.idu-grade-details-dialog/.test(css) &&
    /html\.idu-plus dialog\.idu-grade-details-dialog:not\(\[open\]\)\s*\{[\s\S]*display:\s*none\s*!important;/.test(css),
  "Existing IDU grade descriptions should open in an accessible IDU+ details dialog"
);

assert(
  !/\.innerHTML\s*=|\.outerHTML\s*=|insertAdjacentHTML\s*\(/.test(js),
  "IDU+ should avoid unsafe HTML assignment patterns rejected by extension validators"
);

assert(
  /const observeDynamicContent = \(\) => \{/.test(js) &&
    /new MutationObserver/.test(js) &&
    /dynamicContentTimer = window\.setTimeout/.test(js) &&
    /enhanceDynamicContent\(\);/.test(js) &&
    /dynamicContentObserver\.observe\(document\.body, \{ childList: true, subtree: true \}\)/.test(js),
  "AJAX content should be enhanced through one debounced child-list observer"
);

assert(
  /\.idu-generated, \.idu-select, \.idu-workspace-shell/.test(js),
  "The dynamic observer should ignore UI generated by IDU+ itself"
);

console.log("hidden features and dynamic DOM contract ok");
